/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bonfire-with-marshmallow.glb --draco 
Author: Lillya (https://sketchfab.com/Lillya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/marshmallow-sj-day-16-2bd52b0696b44f1d8765774fd9ea1603
Title: Marshmallow - SJ day 16
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function BonfireWithMarshmallow(props) {
  const { nodes, materials } = useGLTF("models/bonfire-with-marshmallow.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.094, 2.034, -0.178]}
        rotation={[0, -0.238, 0]}
        scale={[1.174, 1.076, 1.174]}
      >
        <mesh geometry={nodes.Object_4.geometry} material={materials.fire} />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.fire}
          position={[0.888, 2.056, 1.234]}
          rotation={[0.098, -0.028, -0.079]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.fire}
          position={[-0.816, 3.316, -0.836]}
          rotation={[-0.112, 0.02, 0.092]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.fire}
          position={[0.765, 3.555, -0.246]}
          rotation={[0.26, 0.026, -0.017]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.fire}
          position={[-0.05, 4.733, 0.248]}
          rotation={[0.16, -0.013, -0.179]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.fire}
          position={[-1.122, 1.316, 0.966]}
          rotation={[-0.035, 0.008, 0.029]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.fire}
          position={[0.083, 0.649, -1.724]}
          rotation={[-0.034, 0.007, 0.028]}
        />
      </group>
      <group
        position={[-1.045, 5.333, 3.237]}
        rotation={[-1.161, 0.451, 3]}
        scale={[0.915, 1.42, 0.915]}
      >
        <mesh geometry={nodes.Object_22.geometry} material={materials.stick} />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.marsh}
          position={[0.029, -1.177, 0.024]}
          rotation={[-0.008, -0.411, -3.104]}
          scale={[1.093, 0.802, 1.093]}
        />
      </group>
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.fire_internal}
        position={[0.094, 1.933, -0.178]}
        rotation={[0, -0.238, 0]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.ashes}
        position={[0, -0.021, 0]}
      />
      <mesh geometry={nodes.Object_26.geometry} material={materials.wood} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.wood} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.wood} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.wood} />
    </group>
  );
}

useGLTF.preload("/bonfire-with-marshmallow.glb");
