/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 g12-shield.glb --draco 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function G12Shield(props) {
  const { nodes, materials } = useGLTF("models//g12-shield.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={
          nodes["tripo_node_a2d84e2a-cf00-42f1-b7ff-b7713fd3899b"].geometry
        }
        material={
          materials["tripo_material_a2d84e2a-cf00-42f1-b7ff-b7713fd3899b"]
        }
      />
    </group>
  );
}

useGLTF.preload("/g12-shield.glb");
