/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 master-guide-women.glb --draco 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MasterGuideWomen(props) {
  const { nodes, materials } = useGLTF("/models/master-guide-women.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={
          nodes["tripo_node_cf19c361-d638-45b6-af45-6c60290c9bf7"].geometry
        }
        material={
          materials["tripo_material_cf19c361-d638-45b6-af45-6c60290c9bf7"]
        }
      />
    </group>
  );
}

useGLTF.preload("/master-guide-women.glb");
