/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pocket_watch.glb --draco 
Author: eucocker (https://sketchfab.com/eucocker)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pocket-watch-a8a270561292434dbf22b7e65e1dcc24
Title: Pocket Watch
*/

"use client";

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function PocketWatch(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/pocket_watch.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="d613d160265e4909aa66ddd44f0b57eafbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="CINEMA_4D_Editor"
                  position={[-227.591, 570.203, 197.439]}
                  rotation={[0, 1.137, -1.088]}
                >
                  <group name="Object_5" />
                </group>
                <group name="Cloth_Surface" />
                <group name="Pocket_Watch_3_obj">
                  <group
                    name="Sphere"
                    position={[0, 37.258, 98.401]}
                    rotation={[-1.919, 0, 0]}
                  >
                    <mesh
                      name="Sphere_default_0"
                      geometry={nodes.Sphere_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Sweep_3_0" position={[-35.509, 0, 0]}>
                    <mesh
                      name="Sweep_3_0_default_0"
                      geometry={nodes.Sweep_3_0_default_0.geometry}
                      material={materials["default"]}
                    />
                    <mesh
                      name="Sweep_3_0_default_0_1"
                      geometry={nodes.Sweep_3_0_default_0_1.geometry}
                      material={materials["default"]}
                    />
                    <mesh
                      name="Sweep_3_0_default_0_2"
                      geometry={nodes.Sweep_3_0_default_0_2.geometry}
                      material={materials["default"]}
                    />
                    <mesh
                      name="Sweep_3_0_default_0_3"
                      geometry={nodes.Sweep_3_0_default_0_3.geometry}
                      material={materials["default"]}
                    />
                    <mesh
                      name="Sweep_3_0_default_0_4"
                      geometry={nodes.Sweep_3_0_default_0_4.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group
                    name="Torus"
                    position={[50.492, 18.189, -176.615]}
                    rotation={[0.088, -0.078, 0.071]}
                  >
                    <mesh
                      name="Torus_default_0"
                      geometry={nodes.Torus_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Subdivision_Surface_1" position={[0, 39.02, 0]}>
                    <mesh
                      name="Subdivision_Surface_1_default_0"
                      geometry={nodes.Subdivision_Surface_1_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Subdivision_Surface" position={[0, 38.089, 0]}>
                    <mesh
                      name="Subdivision_Surface_default_0"
                      geometry={nodes.Subdivision_Surface_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Subdivision_Surface_2" position={[0, 36.821, 0]}>
                    <mesh
                      name="Subdivision_Surface_2_default_0"
                      geometry={nodes.Subdivision_Surface_2_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Null_Cylinder">
                    <mesh
                      name="Null_Cylinder_default_0"
                      geometry={nodes.Null_Cylinder_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Cylinder_1">
                    <mesh
                      name="Cylinder_1_default_0"
                      geometry={nodes.Cylinder_1_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Cylinder_1_1">
                    <mesh
                      name="Cylinder_1_1_default_0"
                      geometry={nodes.Cylinder_1_1_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Sweep">
                    <mesh
                      name="Sweep_default_0"
                      geometry={nodes.Sweep_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Cap_1">
                    <mesh
                      name="Cap_1_default_0"
                      geometry={nodes.Cap_1_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Cap_2">
                    <mesh
                      name="Cap_2_default_0"
                      geometry={nodes.Cap_2_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                  <group name="Lathe">
                    <mesh
                      name="Lathe_default_0"
                      geometry={nodes.Lathe_default_0.geometry}
                      material={materials["default"]}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pocket_watch.glb");
