/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tent.glb --draco 
Author: ARmediaLab (https://sketchfab.com/Daryl.Gungadoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pathfinder-tent-d4297e95f34544c4801dee31afdb2ea2
Title: Pathfinder Tent
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/tent.glb");

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[1.6, 1.6, 1.6]}
      rotation={[0.1, -1, 0]}
      position={[0, 0.8, 0]}
    >
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 4]}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.DefaultMaterial}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/tent.glb");
